<?xml version="1.0" encoding="utf-8"?><Database Name="AIST" Class="DataClassesAistDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IVAN-PPC;Initial Catalog=AIST;Integrated Security=True" SettingsObjectName="AistLabData.Properties.Settings" SettingsPropertyName="AISTConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PACIENT" Member="PACIENTs">
    <Type Name="PACIENT">
      <Column Name="pacient_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="uch" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="KOD_LPU" Type="System.String" DbType="NChar(7)" CanBeNull="true" />
      <Column Name="NOMER_NAPRAV" Type="System.String" DbType="NChar(7)" CanBeNull="true" />
      <Column Name="NAPR_DATA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="kod_ktg" Type="System.String" DbType="NChar(3)" CanBeNull="true" />
      <Column Name="kod_pf" Type="System.String" DbType="NChar(3)" CanBeNull="true" />
      <Column Name="snils" Type="System.String" DbType="NChar(14)" CanBeNull="true" />
      <Column Name="inicial" Type="System.String" DbType="NChar(3)" CanBeNull="true" />
      <Column Name="fio" Type="System.String" DbType="NVarChar(62)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fio1" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="fio2" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="fio3" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="nom_kart" Type="System.String" DbType="NChar(14)" CanBeNull="true" />
      <Column Name="kod_reg" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="kod_regf" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="region" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="regionf" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="str_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="str_idpos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="str_idf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="str_idfpos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="streetf" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="nom_home" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="nom_homef" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="nom_korp" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="nom_korpf" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="nom_flat" Type="System.String" DbType="NChar(4)" CanBeNull="true" />
      <Column Name="nom_flatf" Type="System.String" DbType="NChar(4)" CanBeNull="true" />
      <Column Name="fakt_proj" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="date_rogd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="datpriemtime" Type="System.String" DbType="NVarChar(18)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="vozrast" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="srokberpopriem" Type="System.String" DbType="VarChar(20)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="srokmensis" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="srokposhevelen" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="srokpojvke" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="srokpouzi" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="lpunaprav" Type="System.String" DbType="VarChar(306)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="vippacdata" Type="System.String" DbType="VarChar(16)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="vippackuda" Type="System.String" DbType="VarChar(200)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="adres" Type="System.String" DbType="NVarChar(350)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="adresfakt" Type="System.String" DbType="VarChar(350)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="namestrax" Type="System.String" DbType="VarChar(250)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="inwork" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="professij" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="dlgnp" Type="System.String" DbType="NChar(25)" CanBeNull="true" />
      <Column Name="nom_pol" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="ser_pol" Type="System.String" DbType="NChar(7)" CanBeNull="true" />
      <Column Name="date_pol" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="strax_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="kod_strax" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="kod_dms" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="ser_dms" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="nom_dms" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="kod_socst" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="kod_dokum" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="ser_dokum" Type="System.String" DbType="NChar(8)" CanBeNull="true" />
      <Column Name="nom_dokum" Type="System.String" DbType="NChar(8)" CanBeNull="true" />
      <Column Name="otd_dokum" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OTDDOK_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_dok" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="inval" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="obrazovanie" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="brak_registr" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="n_history" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="data_priem" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="akush_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nacij" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="gr_krovi" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="rezus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="titr" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="titrprop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pedikulez" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="chesotka" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Skleru_glaz" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="god_botkina" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cvet_mochi" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="pechen_uvel" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="koja" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="koja_oblast" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sifilis" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="allergij" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="zdorovo_muja" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="rw" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="rwdata" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rwnomer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="vich" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vichdata" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="vichnomer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hbs" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="hbsdata" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hbsnomer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hbc" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="hbcdata" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hbcnomer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="h_ekstra_zab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="h_tub_zab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="h_tubgod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="h_tubuchet" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="h_ven_zab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="h_botkina_zab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="h_ginek_zab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="h_gemotrans" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="h_gemogod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="h_gemoreak" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="h_reakchto" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="s_ekstra_zab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="s_tub_zab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="s_tubgod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="s_tubuchet" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="s_ven_zab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="s_ginek_zab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mstr_kollet" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="mstr_ustan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mstr_regul" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mstr_obil" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="mstr_bolezn" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="mstr_pokolden" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="mstr_chereskol" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="mstr_pollive" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_dataobsl" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="jk_koljvok" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_srokber" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_vismatki" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_okrjivot" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_ves" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_pribves" Type="System.Decimal" DbType="Decimal(5,1)" CanBeNull="true" />
      <Column Name="jk_adsidj1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_adsidj2" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_adleja1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_adleja2" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_pssidj" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_psleja" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_chastota" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="jk_predlej" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="an_gemoglob" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="an_kreritrocit" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="an_trombocid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="an_belok" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="an_leikocit" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="an_meritrocid" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="an_bakter" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="an_drojgrib" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="anmaz_leikoc" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="anmaz_leikoc1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="anmaz_gonok" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="anmaz_trix" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="anmaz_drojgrib" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="tb_datmstr" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tb_datpshevel" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tb_datjvki" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tb_srber1jvki" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="tb_datuzi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tb_srberuzi" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="tb_kolploduzi" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="tb_mnogovod" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="tb_osloj1pol" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="tb_osllist1" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="tb_osloj2pol" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="tb_osllist2" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="tb_rantoksikoz" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="at_ves" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="at_rost" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_dsp" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_dcr" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_dtr" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_cext" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_okrjivot" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_vismatki" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_isolov" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_kolplodov" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_predlej" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_prdlejchast" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="at_predlejgde" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sf_chastota" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sf_psleja" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sf_adleja1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sf_adleja2" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sf_pssidj" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sf_adsidj1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sf_adsidj2" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sf_chdd" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_sxvatki" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_jalobu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_golboi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_jalobchto" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="do_obsostojnie" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_zrenjsnoe" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_zrprizn" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_zrstadii" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_fizoprnorma" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_fizoprstad" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_mocheisp" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_oteki_yes" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_oteki_prizn" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_belok_moche" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_belokkol" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="do_varikoz_yes" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_varikoz_gde" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="do_izmen_organ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_temperatura" Type="System.Decimal" DbType="Decimal(4,1)" CanBeNull="true" />
      <Column Name="do_sanobr_yes" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_sifilis_yes" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_krovsbor_yes" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_vidvlagal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_vidvlagstadii" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_voduotoshli" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do_datothojdvod" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="do_matka_tonus" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_otdelporajenij" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do_zdorovomuja" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="do1_duxanie" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do1_xrip" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do1_xripsuxoi" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do1_xripjuj" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do1_puzur" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do1_shumplevr" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do1_selezenka" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do1_jiviotuvelich" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do1_jivotmjgki" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do1_jivotnaprjen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do1_jivotvzdut" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do1_jivotnevzdut" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do1_jivotbolezn" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="do1_jboleznobl" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="do1_serdton" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="do1_serdritm" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="do1_serdshum" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="kolrodu" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="otdprochie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="op_tipoper" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="straxprochie" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="straxname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fiopluswork" Type="System.String" DbType="NVarChar(348)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="diagnozpost" Type="System.String" DbType="VarChar(8000)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="do1_serdshum1" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="do1_serdritmtxt" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="do1_serdtontxt" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="diagnvippac" Type="System.String" DbType="VarChar(7000)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="nomberem" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="vvodscaner" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>